services:
  backend:
    build: .
    environment:
      - CHECKPOINT_DB=:memory:
    ports:
      - "8009:8009"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8009/health"]
      interval: 5s
      timeout: 2s
      retries: 5

  smoke-test:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      backend:
        condition: service_healthy
    command: >
      sh -c "pip install requests && python tests/smoke_integration.py"
    environment:
      - BASE_URL=http://backend:8009
