name: Wiki Sync

on:
  push:
    branches:
      - main
    paths:
      - 'docs/wiki/**'

permissions:
  contents: write

concurrency:
  group: wiki-sync
  cancel-in-progress: true

jobs:
  update-wiki:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
        with:
          persist-credentials: false
      - name: Sync wiki
        uses: Andrew-Chen-Wang/github-wiki-action@6448478bd55f1f3f752c93af8ac03207eccc3213
        with:
          path: docs/wiki
          commit-message: "Sync docs/wiki to Wiki"
